-- Bước 1: Vô hiệu hóa kiểm tra khóa ngoại
SET FOREIGN_KEY_CHECKS = 0;

-- Bước 2: Xóa tất cả bảng
DROP TABLE IF EXISTS TaiKhoan;
DROP TABLE IF EXISTS SoDienThoai;
DROP TABLE IF EXISTS Tour;
DROP TABLE IF EXISTS Trip;
DROP TABLE IF EXISTS DonDat;
DROP TABLE IF EXISTS KhuyenMai;
DROP TABLE IF EXISTS ApDung;
DROP TABLE IF EXISTS HuongDanVien;
DROP TABLE IF EXISTS NgoaiNgu;
DROP TABLE IF EXISTS PhuTrach;
DROP TABLE IF EXISTS ThanhToan;
DROP TABLE IF EXISTS DiaDiem;
DROP TABLE IF EXISTS Den;
DROP TABLE IF EXISTS NhaHang;
DROP TABLE IF EXISTS KhachSan;
DROP TABLE IF EXISTS SDTLeTan;
DROP TABLE IF EXISTS DanhGia;

-- Bước 3: Bật lại kiểm tra khóa ngoại
SET FOREIGN_KEY_CHECKS = 1;